require: rubocop-rails

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/20230425180830_devise_create_users.rb
